### ISSUE TITLE
Inference does not get applied

### ISSUE THREAD

**Issue by Birkenpapier** [prs-eth/OverlapPredator#61]
Hello everyone,

thank you very much for your work!
After setting up your project on a Win10 machine with a dedicated conda environment I got following result:
![grafik](https://user-images.githubusercontent.com/11006393/212902211-2a339260-a7a2-43cb-958d-272798f56909.png)

Everything seems to work without problems and I've even got the same message in the terminal regarding numpy as you got. 
But the inference and the overlapping areas are not getting visualized. 
Why is that the case? 

Thank you very much!
Here is also my Cuda version aswell the other dependencies:
![grafik](https://user-images.githubusercontent.com/11006393/212902578-2998ef66-78f8-44d3-8e5e-ba40b504660b.png)

matplotlib==3.3.3
numpy==1.19.4
torch == 1.8.0
torchvision==0.9.0
torchaudio==0.8.0
nibabel==3.2.1
tqdm==4.38.0
open3d==0.10.0.0
easydict==1.9
scipy==1.5.4
coloredlogs==15.0
PyYAML==5.4.1
scikit_learn==0.24.1
tensorboardX==2.1
vtk_visualizer==0.9.6
nibabel==3.2.1
h5py==3.2.1
coloredlogs==15.0
gitpython==3.1.17

Thank you very much for your help!

**Comment by tangqi1012** [comment]
I've encountered the same issue but I don't know what the cause is.

**Comment by Hellcat1005** [comment]
I've encountered the same issue but I don't know what the cause is.

**Comment by lucienchia** [comment]
their demo.py result transformation matrix is a 4X4 identity matrix suggesting that there is no transformation at all.... @ShengyuH may i know why is this so?

**Comment by xl232lx** [comment]
Hello, I have also encountered the situation of poor registration effect, may I ask if you have solved it here？

**Comment by jun3333333** [comment]
Hi there,
I'm currently exploring the model and I've encountered an issue: the links to download the data and weights files seem to be unavailable. If you happen to have these files, could you please share them with me at 2373178085@qq.com? I'd greatly appreciate your assistance. Thank you so much!!

**Comment by jun3333333** [comment]
Hello, I encountered a FileNotFoundError after running: [Errno 2] No such file or directory: 'snapshot/indoor/est_traj/3DMatch/250/7-scenes-redkitchen/est.log'， There should be no predicted samples. If you have, please send a snapshot to my email: 2373178085@qq.com

**Comment by jun3333333** [comment]
snapshot/indoor/est_traj/3DMatch/250
0it [00:00, ?it/s]
gt_folder: configs/benchmarks/3DMatch
exp_dir: snapshot/indoor/est_traj/3DMatch/250
tsfm_est shape: (0,)
tsfm_est: []
Scene names: ['7-scenes-redkitchen', 'sun3d-home_at-home_at_scan1_2013_jan_1', 'sun3d-home_md-home_md_scan9_2012_sep_30', 'sun3d-hotel_uc-scan3', 'sun3d-hotel_umd-maryland_hotel1', 'sun3d-hotel_umd-maryland_hotel3', 'sun3d-mit_76_studyroom-76-1studyroom2', 'sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika']
Scene: 7-scenes-redkitchen, GT pairs: 506
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-home_at-home_at_scan1_2013_jan_1, GT pairs: 156
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-home_md-home_md_scan9_2012_sep_30, GT pairs: 208
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_uc-scan3, GT pairs: 226
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_umd-maryland_hotel1, GT pairs: 104
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_umd-maryland_hotel3, GT pairs: 54
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-mit_76_studyroom-76-1studyroom2, GT pairs: 292
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika, GT pairs: 77
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Traceback (most recent call last):
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 124, in <module>
    benchmark_predator(feats_scores, args.n_points, args.exp_dir, args.benchmark)
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 85, in benchmark_predator
    benchmark(exp_dir, gt_folder)
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark.py", line 304, in benchmark
    re = rotation_error(torch.from_numpy(ext_gt_traj[:,0:3,0:3]), torch.from_numpy(est_traj[:,0:3,0:3])).cpu().numpy()[np.array(c_flag)==0]
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark.py", line 27, in rotation_error
    e = torch.stack([(torch.trace(R_[_, :, :]) - 1) / 2 for _ in range(R_.shape[0])], dim=0).unsqueeze(1)
RuntimeError: stack expects a non-empty TensorList
snapshot/indoor/est_traj/3DMatch/500
0it [00:00, ?it/s]
gt_folder: configs/benchmarks/3DMatch
exp_dir: snapshot/indoor/est_traj/3DMatch/500
tsfm_est shape: (0,)
tsfm_est: []
Scene names: ['7-scenes-redkitchen', 'sun3d-home_at-home_at_scan1_2013_jan_1', 'sun3d-home_md-home_md_scan9_2012_sep_30', 'sun3d-hotel_uc-scan3', 'sun3d-hotel_umd-maryland_hotel1', 'sun3d-hotel_umd-maryland_hotel3', 'sun3d-mit_76_studyroom-76-1studyroom2', 'sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika']
Scene: 7-scenes-redkitchen, GT pairs: 506
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-home_at-home_at_scan1_2013_jan_1, GT pairs: 156
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-home_md-home_md_scan9_2012_sep_30, GT pairs: 208
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_uc-scan3, GT pairs: 226
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_umd-maryland_hotel1, GT pairs: 104
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_umd-maryland_hotel3, GT pairs: 54
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-mit_76_studyroom-76-1studyroom2, GT pairs: 292
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika, GT pairs: 77
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Traceback (most recent call last):
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 124, in <module>
    benchmark_predator(feats_scores, args.n_points, args.exp_dir, args.benchmark)
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 85, in benchmark_predator
    benchmark(exp_dir, gt_folder)
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark.py", line 304, in benchmark
    re = rotation_error(torch.from_numpy(ext_gt_traj[:,0:3,0:3]), torch.from_numpy(est_traj[:,0:3,0:3])).cpu().numpy()[np.array(c_flag)==0]
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark.py", line 27, in rotation_error
    e = torch.stack([(torch.trace(R_[_, :, :]) - 1) / 2 for _ in range(R_.shape[0])], dim=0).unsqueeze(1)
RuntimeError: stack expects a non-empty TensorList
snapshot/indoor/est_traj/3DMatch/1000
0it [00:00, ?it/s]
gt_folder: configs/benchmarks/3DMatch
exp_dir: snapshot/indoor/est_traj/3DMatch/1000
tsfm_est shape: (0,)
tsfm_est: []
Scene names: ['7-scenes-redkitchen', 'sun3d-home_at-home_at_scan1_2013_jan_1', 'sun3d-home_md-home_md_scan9_2012_sep_30', 'sun3d-hotel_uc-scan3', 'sun3d-hotel_umd-maryland_hotel1', 'sun3d-hotel_umd-maryland_hotel3', 'sun3d-mit_76_studyroom-76-1studyroom2', 'sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika']
Scene: 7-scenes-redkitchen, GT pairs: 506
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-home_at-home_at_scan1_2013_jan_1, GT pairs: 156
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-home_md-home_md_scan9_2012_sep_30, GT pairs: 208
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_uc-scan3, GT pairs: 226
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_umd-maryland_hotel1, GT pairs: 104
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_umd-maryland_hotel3, GT pairs: 54
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-mit_76_studyroom-76-1studyroom2, GT pairs: 292
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika, GT pairs: 77
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Traceback (most recent call last):
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 124, in <module>
    benchmark_predator(feats_scores, args.n_points, args.exp_dir, args.benchmark)
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 85, in benchmark_predator
    benchmark(exp_dir, gt_folder)
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark.py", line 304, in benchmark
    re = rotation_error(torch.from_numpy(ext_gt_traj[:,0:3,0:3]), torch.from_numpy(est_traj[:,0:3,0:3])).cpu().numpy()[np.array(c_flag)==0]
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark.py", line 27, in rotation_error
    e = torch.stack([(torch.trace(R_[_, :, :]) - 1) / 2 for _ in range(R_.shape[0])], dim=0).unsqueeze(1)
RuntimeError: stack expects a non-empty TensorList
snapshot/indoor/est_traj/3DMatch/2500
0it [00:00, ?it/s]
gt_folder: configs/benchmarks/3DMatch
exp_dir: snapshot/indoor/est_traj/3DMatch/2500
tsfm_est shape: (0,)
tsfm_est: []
Scene names: ['7-scenes-redkitchen', 'sun3d-home_at-home_at_scan1_2013_jan_1', 'sun3d-home_md-home_md_scan9_2012_sep_30', 'sun3d-hotel_uc-scan3', 'sun3d-hotel_umd-maryland_hotel1', 'sun3d-hotel_umd-maryland_hotel3', 'sun3d-mit_76_studyroom-76-1studyroom2', 'sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika']
Scene: 7-scenes-redkitchen, GT pairs: 506
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-home_at-home_at_scan1_2013_jan_1, GT pairs: 156
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-home_md-home_md_scan9_2012_sep_30, GT pairs: 208
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_uc-scan3, GT pairs: 226
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_umd-maryland_hotel1, GT pairs: 104
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_umd-maryland_hotel3, GT pairs: 54
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-mit_76_studyroom-76-1studyroom2, GT pairs: 292
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika, GT pairs: 77
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Traceback (most recent call last):
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 124, in <module>
    benchmark_predator(feats_scores, args.n_points, args.exp_dir, args.benchmark)
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 85, in benchmark_predator
    benchmark(exp_dir, gt_folder)
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark.py", line 304, in benchmark
    re = rotation_error(torch.from_numpy(ext_gt_traj[:,0:3,0:3]), torch.from_numpy(est_traj[:,0:3,0:3])).cpu().numpy()[np.array(c_flag)==0]
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark.py", line 27, in rotation_error
    e = torch.stack([(torch.trace(R_[_, :, :]) - 1) / 2 for _ in range(R_.shape[0])], dim=0).unsqueeze(1)
RuntimeError: stack expects a non-empty TensorList
snapshot/indoor/est_traj/3DMatch/5000
0it [00:00, ?it/s]
gt_folder: configs/benchmarks/3DMatch
exp_dir: snapshot/indoor/est_traj/3DMatch/5000
tsfm_est shape: (0,)
tsfm_est: []
Scene names: ['7-scenes-redkitchen', 'sun3d-home_at-home_at_scan1_2013_jan_1', 'sun3d-home_md-home_md_scan9_2012_sep_30', 'sun3d-hotel_uc-scan3', 'sun3d-hotel_umd-maryland_hotel1', 'sun3d-hotel_umd-maryland_hotel3', 'sun3d-mit_76_studyroom-76-1studyroom2', 'sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika']
Scene: 7-scenes-redkitchen, GT pairs: 506
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-home_at-home_at_scan1_2013_jan_1, GT pairs: 156
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-home_md-home_md_scan9_2012_sep_30, GT pairs: 208
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_uc-scan3, GT pairs: 226
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_umd-maryland_hotel1, GT pairs: 104
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_umd-maryland_hotel3, GT pairs: 54
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-mit_76_studyroom-76-1studyroom2, GT pairs: 292
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika, GT pairs: 77
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Traceback (most recent call last):
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 124, in <module>
    benchmark_predator(feats_scores, args.n_points, args.exp_dir, args.benchmark)
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 85, in benchmark_predator
    benchmark(exp_dir, gt_folder)
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark.py", line 304, in benchmark
    re = rotation_error(torch.from_numpy(ext_gt_traj[:,0:3,0:3]), torch.from_numpy(est_traj[:,0:3,0:3])).cpu().numpy()[np.array(c_flag)==0]
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark.py", line 27, in rotation_error
    e = torch.stack([(torch.trace(R_[_, :, :]) - 1) / 2 for _ in range(R_.shape[0])], dim=0).unsqueeze(1)
RuntimeError: stack expects a non-empty TensorList
(pytorch1) user@user-System-Product-Name:~/OverlapPredator.Mink-master$ for N_POINTS in 250 500 1000 2500 5000
do
  python scripts/evaluate_predator.py --source_path snapshot/indoor/3DMatch --n_points $N_POINTS --benchmark 3DMatch --exp_dir snapshot/indoor/est_traj --sampling prob
done
snapshot/indoor/est_traj/3DMatch/250
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 124, in <module>
    benchmark_predator(feats_scores, args.n_points, args.exp_dir, args.benchmark)
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 81, in benchmark_predator
    write_est_trajectory(gt_folder, exp_dir, tsfm_est)
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark_utils.py", line 67, in write_est_trajectory
    est_traj.append(tsfm_est[count])
IndexError: index 0 is out of bounds for axis 0 with size 0
snapshot/indoor/est_traj/3DMatch/500
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 124, in <module>
    benchmark_predator(feats_scores, args.n_points, args.exp_dir, args.benchmark)
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 81, in benchmark_predator
    write_est_trajectory(gt_folder, exp_dir, tsfm_est)
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark_utils.py", line 67, in write_est_trajectory
    est_traj.append(tsfm_est[count])
IndexError: index 0 is out of bounds for axis 0 with size 0
snapshot/indoor/est_traj/3DMatch/1000
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 124, in <module>
    benchmark_predator(feats_scores, args.n_points, args.exp_dir, args.benchmark)
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 81, in benchmark_predator
    write_est_trajectory(gt_folder, exp_dir, tsfm_est)
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark_utils.py", line 67, in write_est_trajectory
    est_traj.append(tsfm_est[count])
IndexError: index 0 is out of bounds for axis 0 with size 0
snapshot/indoor/est_traj/3DMatch/2500
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 124, in <module>
    benchmark_predator(feats_scores, args.n_points, args.exp_dir, args.benchmark)
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 81, in benchmark_predator
    write_est_trajectory(gt_folder, exp_dir, tsfm_est)
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark_utils.py", line 67, in write_est_trajectory
    est_traj.append(tsfm_est[count])
IndexError: index 0 is out of bounds for axis 0 with size 0
snapshot/indoor/est_traj/3DMatch/5000
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 124, in <module>
    benchmark_predator(feats_scores, args.n_points, args.exp_dir, args.benchmark)
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 81, in benchmark_predator
    write_est_trajectory(gt_folder, exp_dir, tsfm_est)
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark_utils.py", line 67, in write_est_trajectory
    est_traj.append(tsfm_est[count])
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by jun3333333** [comment]
作者您好，我用自己的源云和目标云文件运行 demo.py 进行注册，效果不是很好，请问如何提高我的注册效果，请发到我的邮箱：2373178085@qq.com
