### ISSUE TITLE
I want to know where to download 3dmatch dataset in .pth format?

### ISSUE THREAD

**Issue by superYuezhang** [prs-eth/OverlapPredator#71]
The 3dmatch dataset download link for this repository give us the dataset in .ply format, and the folder branch doesn't match the path in .pkl file. Where should I download the dataset in .pth format corresponding to the .pkl file?

**Comment by lucienchia** [comment]
im facing this as well, anyone knows how to get them?

**Comment by hiyyg** [comment]
Same question here.

**Comment by rhyme111** [comment]
Hello, I'm not sure why I can't open this link right now. Can you still access it?

**Comment by rhyme111** [comment]
> Hello, i think i found the dataset, it is in https://share.phys.ethz.ch/~gsg/Predator/.
> 
> The way it is organized is different but the content is correct.

Hello, I'm not sure why I can't open this link right now. Can you still access it?

**Comment by rhyme111** [comment]
> I just tried to acces but I can't either, i got it from the official website of overlap Predator, but it seems doesn't work anymore. I read it has happened before, maybe trying another time works as in [#78](https://github.com/prs-eth/OverlapPredator/issues/78).

I see. Thank you so much.

**Comment by rhyme111** [comment]
> I just tried to acces but I can't either, i got it from the official website of overlap Predator, but it seems doesn't work anymore. I read it has happened before, maybe trying another time works as in [#78](https://github.com/prs-eth/OverlapPredator/issues/78).

Hello, the link has still not been restored. I urgently need the data from data.zip and weights.zip. If you have these files, could you please send them to my email? My email is zmh2245749337@gmail.com. Thank you very much!

**Comment by ElKerri14** [comment]
I didn't download the weights, only the 3D data, it is 5.4 GB in ZIP, i'll try to send it to you as a onedrive link.

**Comment by rhyme111** [comment]
> I didn't download the weights, only the 3D data, it is 5.4 GB in ZIP, i'll try to send it to you as a onedrive link.

You’ve been a huge help, thank you so much!

**Comment by soosoonet** [comment]
Hi there, 
I'm currently exploring the model and I've encountered an issue: the links to download the data and weights files seem to be unavailable. If you happen to have these files, could you please share them with me at changbumlee1415@gmail.com? I'd greatly appreciate your assistance. Thank you so much!!

**Comment by ElKerri14** [comment]
Hello, as I said before sadly I didn't download the weights and only have the 3D data, i'll send it to you as a onedrive link.

**Comment by heiheideliuri** [comment]
> > 我没有下载权重，只下载了 3D 数据，它的 ZIP 格式为 5.4 GB，我将尝试将其作为 onedrive 链接发送给您。
> 
> 你们帮了大忙，非常感谢你们！



> > 我没有下载权重，只下载了 3D 数据，它的 ZIP 格式为 5.4 GB，我将尝试将其作为 onedrive 链接发送给您。
> 
> 你们帮了大忙，非常感谢你们！

Hello, can you share with me a 3dmatch data set of.pth file? I really need it urgently, thank you！leeadah0427@gmail.com

**Comment by heiheideliuri** [comment]
> 您好，正如我之前所说，遗憾的是我没有下载权重，只有 3D 数据，我会将其作为 onedrive 链接发送给您。



> Hello, as I said before sadly I didn't download the weights and only have the 3D data, i'll send it to you as a onedrive link.

Hello, can you share with me a 3dmatch data set of.pth file? I really need it urgently, thank you！[leeadah0427@gmail.com](mailto:leeadah0427@gmail.com)

**Comment by ElKerri14** [comment]
Hello, I sent you an email.

**Comment by heiheideliuri** [comment]
> Hello, I sent you an email.

Thank you so much！！

**Comment by ABCBeacuse** [comment]
> Hello, I sent you an email.

Hello, I have also encountered this issue, the current download link is returning a 404 error. 
I would greatly appreciate it if you could send me the 3dmatch.zip file. My email address is 1305198449@qq.com. Thank you very much for your assistance.

**Comment by ElKerri14** [comment]
Hello, I shared you the data via email.

**Comment by ABCBeacuse** [comment]
> Hello, I shared you the data via email.

Ok, Thank you so much for sending it to me. I have received it.•ᴗ•

**Comment by Aqu495** [comment]
> 我没有下载权重，只下载了 3D 数据，它的 ZIP 格式为 5.4 GB，我将尝试将其作为 onedrive 链接发送给您。

Hello, I also encountered the issue of being unable to download the data. Could you please share a copy with me at my email **[2896422489@qq.com](mailto:2896422489@qq.com)**? I would really appreciate it! Thank you very much!

**Comment by milkleaves** [comment]
> Hello, I shared you the data via email.

Hello, I also have this problem, can you send me the 3Dmatch dataset please. My email address is milkleave@gmail.com. Thank you very much!

**Comment by ElKerri14** [comment]
Hello, I sent you an email with the data.

**Comment by milkleaves** [comment]
> Hello, I sent you an email with the data.
Thank you very much!

**Comment by YJM-00** [comment]
> 您好，我通过电子邮件分享了您的数据。
您好，我也无法打开3dmatch的.pth格式的数据集，请问您能发到我的邮箱吗，我十分感谢，我的邮箱：1649023115@qq.com

**Comment by YJM-00** [comment]
> > 您好，我通过电子邮件分享了您的数据。
> 
> 您好，我也有这个问题，您能把 3Dmatch 数据集发给我吗？我的电子邮件地址是 [milkleave@gmail.com](mailto:milkleave@gmail.com)。谢谢！

您好，我也无法打开3dmatch的.pth格式的数据集，请问您能发到我的邮箱吗，我十分感谢，我的邮箱：1649023115@qq.com

**Comment by YJM-00** [comment]
> > 您好，我给您发了一封电子邮件。
> 
> 您好，我也遇到了这个问题，当前下载链接返回 404 错误。如果您能将 3dmatch.zip 文件发送给我，我将不胜感激。我的电子邮件地址是 [1305198449@qq.com](mailto:1305198449@qq.com)。非常感谢您的帮助。

您好，我也无法打开3dmatch的.pth格式的数据集，请问您能发到我的邮箱吗，我十分感谢，我的邮箱：[1649023115@qq.com](mailto:1649023115@qq.com)

**Comment by milkleaves** [comment]
I found that after changing “~gsg” to “~gseg” in the download link, it downloads fine, so you can try it.

**Comment by jun3333333** [comment]
Hi there,
I'm currently exploring the model and I've encountered an issue: the links to download the data and weights files seem to be unavailable. If you happen to have these files, could you please share them with me at 2373178085@qq.com? I'd greatly appreciate your assistance. Thank you so much!!

**Comment by Gfondf** [comment]
> 我发现将下载链接中的“~gsg”改为“~gseg”后，下载就可以了，所以你可以试试。

That's great, brother.

**Comment by jun3333333** [comment]
you are good





---Original---
From: ***@***.***&gt;
Date: Wed, Mar 19, 2025 11:14 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [prs-eth/OverlapPredator] I want to know where to download3dmatch dataset in .pth format? (Issue #71)


    
我发现将下载链接中的“~gsg”改为“~gseg”后，下载就可以了，所以你可以试试。
  
That's great, brother.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;
  Gfondf left a comment (prs-eth/OverlapPredator#71)
  
我发现将下载链接中的“~gsg”改为“~gseg”后，下载就可以了，所以你可以试试。
  
That's great, brother.

**Comment by Gfondf** [comment]
thank you very much！



---Original---
From: ***@***.***&gt;
Date: Wed, Mar 19, 2025 11:17 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [prs-eth/OverlapPredator] I want to know where to download3dmatch dataset in .pth format? (Issue #71)


   you are good <br&gt; <br&gt; <br&gt; <br&gt; <br&gt; <br&gt; ---Original--- <br&gt; From: ***@***.***&amp;amp;gt; <br&gt; Date: Wed, Mar 19, 2025 11:14 AM <br&gt; To: ***@***.***&amp;amp;gt;; <br&gt; Cc: ***@***.******@***.***&amp;amp;gt;; <br&gt; Subject: Re: [prs-eth/OverlapPredator] I want to know where to download3dmatch dataset in .pth format? (Issue #71) <br&gt; <br&gt; <br&gt;      <br&gt; 我发现将下载链接中的“~gsg”改为“~gseg”后，下载就可以了，所以你可以试试。 <br&gt;    <br&gt; That&amp;#39;s great, brother. <br&gt; <br&gt; — <br&gt; Reply to this email directly, view it on GitHub, or unsubscribe. <br&gt; You are receiving this because you commented.Message ID: ***@***.***&amp;amp;gt; <br&gt;   Gfondf left a comment (prs-eth/OverlapPredator#71) <br&gt;    <br&gt; 我发现将下载链接中的“~gsg”改为“~gseg”后，下载就可以了，所以你可以试试。 <br&gt;    <br&gt; That&amp;#39;s great, brother. <br&gt;   <br&gt; — <br&gt; Reply to this email directly, view it on GitHub, or unsubscribe. <br&gt; You are receiving this because you commented.Message ID: ***@***.***&amp;amp;gt;
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;
  jun3333333 left a comment (prs-eth/OverlapPredator#71)
 you are good <br&gt; <br&gt; <br&gt; <br&gt; <br&gt; <br&gt; ---Original--- <br&gt; From: ***@***.***&amp;amp;gt; <br&gt; Date: Wed, Mar 19, 2025 11:14 AM <br&gt; To: ***@***.***&amp;amp;gt;; <br&gt; Cc: ***@***.******@***.***&amp;amp;gt;; <br&gt; Subject: Re: [prs-eth/OverlapPredator] I want to know where to download3dmatch dataset in .pth format? (Issue #71) <br&gt; <br&gt; <br&gt;      <br&gt; 我发现将下载链接中的“~gsg”改为“~gseg”后，下载就可以了，所以你可以试试。 <br&gt;    <br&gt; That&amp;#39;s great, brother. <br&gt; <br&gt; — <br&gt; Reply to this email directly, view it on GitHub, or unsubscribe. <br&gt; You are receiving this because you commented.Message ID: ***@***.***&amp;amp;gt; <br&gt;   Gfondf left a comment (prs-eth/OverlapPredator#71) <br&gt;    <br&gt; 我发现将下载链接中的“~gsg”改为“~gseg”后，下载就可以了，所以你可以试试。 <br&gt;    <br&gt; That&amp;#39;s great, brother. <br&gt;   <br&gt; — <br&gt; Reply to this email directly, view it on GitHub, or unsubscribe. <br&gt; You are receiving this because you commented.Message ID: ***@***.***&amp;amp;gt;

**Comment by jun3333333** [comment]
snapshot/indoor/est_traj/3DMatch/250
0it [00:00, ?it/s]
gt_folder: configs/benchmarks/3DMatch
exp_dir: snapshot/indoor/est_traj/3DMatch/250
tsfm_est shape: (0,)
tsfm_est: []
Scene names: ['7-scenes-redkitchen', 'sun3d-home_at-home_at_scan1_2013_jan_1', 'sun3d-home_md-home_md_scan9_2012_sep_30', 'sun3d-hotel_uc-scan3', 'sun3d-hotel_umd-maryland_hotel1', 'sun3d-hotel_umd-maryland_hotel3', 'sun3d-mit_76_studyroom-76-1studyroom2', 'sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika']
Scene: 7-scenes-redkitchen, GT pairs: 506
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-home_at-home_at_scan1_2013_jan_1, GT pairs: 156
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-home_md-home_md_scan9_2012_sep_30, GT pairs: 208
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_uc-scan3, GT pairs: 226
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_umd-maryland_hotel1, GT pairs: 104
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_umd-maryland_hotel3, GT pairs: 54
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-mit_76_studyroom-76-1studyroom2, GT pairs: 292
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika, GT pairs: 77
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Traceback (most recent call last):
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 124, in <module>
    benchmark_predator(feats_scores, args.n_points, args.exp_dir, args.benchmark)
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 85, in benchmark_predator
    benchmark(exp_dir, gt_folder)
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark.py", line 304, in benchmark
    re = rotation_error(torch.from_numpy(ext_gt_traj[:,0:3,0:3]), torch.from_numpy(est_traj[:,0:3,0:3])).cpu().numpy()[np.array(c_flag)==0]
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark.py", line 27, in rotation_error
    e = torch.stack([(torch.trace(R_[_, :, :]) - 1) / 2 for _ in range(R_.shape[0])], dim=0).unsqueeze(1)
RuntimeError: stack expects a non-empty TensorList
snapshot/indoor/est_traj/3DMatch/500
0it [00:00, ?it/s]
gt_folder: configs/benchmarks/3DMatch
exp_dir: snapshot/indoor/est_traj/3DMatch/500
tsfm_est shape: (0,)
tsfm_est: []
Scene names: ['7-scenes-redkitchen', 'sun3d-home_at-home_at_scan1_2013_jan_1', 'sun3d-home_md-home_md_scan9_2012_sep_30', 'sun3d-hotel_uc-scan3', 'sun3d-hotel_umd-maryland_hotel1', 'sun3d-hotel_umd-maryland_hotel3', 'sun3d-mit_76_studyroom-76-1studyroom2', 'sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika']
Scene: 7-scenes-redkitchen, GT pairs: 506
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-home_at-home_at_scan1_2013_jan_1, GT pairs: 156
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-home_md-home_md_scan9_2012_sep_30, GT pairs: 208
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_uc-scan3, GT pairs: 226
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_umd-maryland_hotel1, GT pairs: 104
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_umd-maryland_hotel3, GT pairs: 54
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-mit_76_studyroom-76-1studyroom2, GT pairs: 292
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika, GT pairs: 77
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Traceback (most recent call last):
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 124, in <module>
    benchmark_predator(feats_scores, args.n_points, args.exp_dir, args.benchmark)
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 85, in benchmark_predator
    benchmark(exp_dir, gt_folder)
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark.py", line 304, in benchmark
    re = rotation_error(torch.from_numpy(ext_gt_traj[:,0:3,0:3]), torch.from_numpy(est_traj[:,0:3,0:3])).cpu().numpy()[np.array(c_flag)==0]
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark.py", line 27, in rotation_error
    e = torch.stack([(torch.trace(R_[_, :, :]) - 1) / 2 for _ in range(R_.shape[0])], dim=0).unsqueeze(1)
RuntimeError: stack expects a non-empty TensorList
snapshot/indoor/est_traj/3DMatch/1000
0it [00:00, ?it/s]
gt_folder: configs/benchmarks/3DMatch
exp_dir: snapshot/indoor/est_traj/3DMatch/1000
tsfm_est shape: (0,)
tsfm_est: []
Scene names: ['7-scenes-redkitchen', 'sun3d-home_at-home_at_scan1_2013_jan_1', 'sun3d-home_md-home_md_scan9_2012_sep_30', 'sun3d-hotel_uc-scan3', 'sun3d-hotel_umd-maryland_hotel1', 'sun3d-hotel_umd-maryland_hotel3', 'sun3d-mit_76_studyroom-76-1studyroom2', 'sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika']
Scene: 7-scenes-redkitchen, GT pairs: 506
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-home_at-home_at_scan1_2013_jan_1, GT pairs: 156
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-home_md-home_md_scan9_2012_sep_30, GT pairs: 208
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_uc-scan3, GT pairs: 226
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_umd-maryland_hotel1, GT pairs: 104
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_umd-maryland_hotel3, GT pairs: 54
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-mit_76_studyroom-76-1studyroom2, GT pairs: 292
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika, GT pairs: 77
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Traceback (most recent call last):
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 124, in <module>
    benchmark_predator(feats_scores, args.n_points, args.exp_dir, args.benchmark)
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 85, in benchmark_predator
    benchmark(exp_dir, gt_folder)
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark.py", line 304, in benchmark
    re = rotation_error(torch.from_numpy(ext_gt_traj[:,0:3,0:3]), torch.from_numpy(est_traj[:,0:3,0:3])).cpu().numpy()[np.array(c_flag)==0]
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark.py", line 27, in rotation_error
    e = torch.stack([(torch.trace(R_[_, :, :]) - 1) / 2 for _ in range(R_.shape[0])], dim=0).unsqueeze(1)
RuntimeError: stack expects a non-empty TensorList
snapshot/indoor/est_traj/3DMatch/2500
0it [00:00, ?it/s]
gt_folder: configs/benchmarks/3DMatch
exp_dir: snapshot/indoor/est_traj/3DMatch/2500
tsfm_est shape: (0,)
tsfm_est: []
Scene names: ['7-scenes-redkitchen', 'sun3d-home_at-home_at_scan1_2013_jan_1', 'sun3d-home_md-home_md_scan9_2012_sep_30', 'sun3d-hotel_uc-scan3', 'sun3d-hotel_umd-maryland_hotel1', 'sun3d-hotel_umd-maryland_hotel3', 'sun3d-mit_76_studyroom-76-1studyroom2', 'sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika']
Scene: 7-scenes-redkitchen, GT pairs: 506
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-home_at-home_at_scan1_2013_jan_1, GT pairs: 156
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-home_md-home_md_scan9_2012_sep_30, GT pairs: 208
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_uc-scan3, GT pairs: 226
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_umd-maryland_hotel1, GT pairs: 104
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_umd-maryland_hotel3, GT pairs: 54
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-mit_76_studyroom-76-1studyroom2, GT pairs: 292
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika, GT pairs: 77
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Traceback (most recent call last):
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 124, in <module>
    benchmark_predator(feats_scores, args.n_points, args.exp_dir, args.benchmark)
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 85, in benchmark_predator
    benchmark(exp_dir, gt_folder)
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark.py", line 304, in benchmark
    re = rotation_error(torch.from_numpy(ext_gt_traj[:,0:3,0:3]), torch.from_numpy(est_traj[:,0:3,0:3])).cpu().numpy()[np.array(c_flag)==0]
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark.py", line 27, in rotation_error
    e = torch.stack([(torch.trace(R_[_, :, :]) - 1) / 2 for _ in range(R_.shape[0])], dim=0).unsqueeze(1)
RuntimeError: stack expects a non-empty TensorList
snapshot/indoor/est_traj/3DMatch/5000
0it [00:00, ?it/s]
gt_folder: configs/benchmarks/3DMatch
exp_dir: snapshot/indoor/est_traj/3DMatch/5000
tsfm_est shape: (0,)
tsfm_est: []
Scene names: ['7-scenes-redkitchen', 'sun3d-home_at-home_at_scan1_2013_jan_1', 'sun3d-home_md-home_md_scan9_2012_sep_30', 'sun3d-hotel_uc-scan3', 'sun3d-hotel_umd-maryland_hotel1', 'sun3d-hotel_umd-maryland_hotel3', 'sun3d-mit_76_studyroom-76-1studyroom2', 'sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika']
Scene: 7-scenes-redkitchen, GT pairs: 506
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-home_at-home_at_scan1_2013_jan_1, GT pairs: 156
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-home_md-home_md_scan9_2012_sep_30, GT pairs: 208
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_uc-scan3, GT pairs: 226
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_umd-maryland_hotel1, GT pairs: 104
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_umd-maryland_hotel3, GT pairs: 54
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-mit_76_studyroom-76-1studyroom2, GT pairs: 292
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika, GT pairs: 77
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Traceback (most recent call last):
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 124, in <module>
    benchmark_predator(feats_scores, args.n_points, args.exp_dir, args.benchmark)
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 85, in benchmark_predator
    benchmark(exp_dir, gt_folder)
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark.py", line 304, in benchmark
    re = rotation_error(torch.from_numpy(ext_gt_traj[:,0:3,0:3]), torch.from_numpy(est_traj[:,0:3,0:3])).cpu().numpy()[np.array(c_flag)==0]
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark.py", line 27, in rotation_error
    e = torch.stack([(torch.trace(R_[_, :, :]) - 1) / 2 for _ in range(R_.shape[0])], dim=0).unsqueeze(1)
RuntimeError: stack expects a non-empty TensorList
(pytorch1) user@user-System-Product-Name:~/OverlapPredator.Mink-master$ for N_POINTS in 250 500 1000 2500 5000
do
  python scripts/evaluate_predator.py --source_path snapshot/indoor/3DMatch --n_points $N_POINTS --benchmark 3DMatch --exp_dir snapshot/indoor/est_traj --sampling prob
done
snapshot/indoor/est_traj/3DMatch/250
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 124, in <module>
    benchmark_predator(feats_scores, args.n_points, args.exp_dir, args.benchmark)
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 81, in benchmark_predator
    write_est_trajectory(gt_folder, exp_dir, tsfm_est)
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark_utils.py", line 67, in write_est_trajectory
    est_traj.append(tsfm_est[count])
IndexError: index 0 is out of bounds for axis 0 with size 0
snapshot/indoor/est_traj/3DMatch/500
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 124, in <module>
    benchmark_predator(feats_scores, args.n_points, args.exp_dir, args.benchmark)
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 81, in benchmark_predator
    write_est_trajectory(gt_folder, exp_dir, tsfm_est)
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark_utils.py", line 67, in write_est_trajectory
    est_traj.append(tsfm_est[count])
IndexError: index 0 is out of bounds for axis 0 with size 0
snapshot/indoor/est_traj/3DMatch/1000
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 124, in <module>
    benchmark_predator(feats_scores, args.n_points, args.exp_dir, args.benchmark)
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 81, in benchmark_predator
    write_est_trajectory(gt_folder, exp_dir, tsfm_est)
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark_utils.py", line 67, in write_est_trajectory
    est_traj.append(tsfm_est[count])
IndexError: index 0 is out of bounds for axis 0 with size 0
snapshot/indoor/est_traj/3DMatch/2500
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 124, in <module>
    benchmark_predator(feats_scores, args.n_points, args.exp_dir, args.benchmark)
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 81, in benchmark_predator
    write_est_trajectory(gt_folder, exp_dir, tsfm_est)
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark_utils.py", line 67, in write_est_trajectory
    est_traj.append(tsfm_est[count])
IndexError: index 0 is out of bounds for axis 0 with size 0
snapshot/indoor/est_traj/3DMatch/5000
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 124, in <module>
    benchmark_predator(feats_scores, args.n_points, args.exp_dir, args.benchmark)
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 81, in benchmark_predator
    write_est_trajectory(gt_folder, exp_dir, tsfm_est)
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark_utils.py", line 67, in write_est_trajectory
    est_traj.append(tsfm_est[count])
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by ye0905** [comment]
> 您好，我通过电子邮件分享了您的数据。

Hello, I have also encountered this issue, the current download link is returning a 404 error.
I would greatly appreciate it if you could send me the 3dmatch.zip file. My email address is [1305198449@qq.com](mailto:2569580670@qq.com). Thank you very much for your assistance.

**Comment by brianavila72** [comment]
Hi @ElKerri14, I have also encountered this issue, the current download link is still returning a 404 error.
I would be very grateful if you could share the 3dmatch.zip file with me. My email address is brianavila72@gmail.com. Thank you very much for your help.

**Comment by ABCBeacuse** [comment]
I have sent it. Have you received it?


咩咩咩啊
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "prs-eth/OverlapPredator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年4月30日(星期三) 下午5:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [prs-eth/OverlapPredator] I want to know where to download 3dmatch dataset in .pth format? (Issue #71)



 brianavila72 left a comment (prs-eth/OverlapPredator#71)
 
Hi @ElKerri14, I have also encountered this issue, the current download link is still returning a 404 error.
 I would be very grateful if you could share the 3dmatch.zip file with me. My email address is ***@***.*** Thank you very much for your help.

**Comment by jun3333333** [comment]
Hello author, I use my own source cloud and target cloud files to run demo.py for registration, the effect is not very good, may I ask how I can improve my registration effect？，Please send it to my email：2373178085@qq.com

**Comment by cy94** [comment]
Hello @ABCBeacuse @milkleaves @ElKerri14 I'm not able to access this dataset now, could you please share the link with me as well on [chandan.yeshwanth@tum.de](chandan.yeshwanth@tum.de)?
Thank you :)

**Comment by zjr-ustc** [comment]
Hi  @ABCBeacuse @milkleaves @ElKerri14, I have also encountered this issue, the current download link is still returning a 404 error.
I would be very grateful if you could share the 3dmatch.zip file with me. My email address is 1426455192@qq.com . Thank you very much for your help.

**Comment by ElKerri14** [comment]
Hello, @cy94 @zjr-ustc I just re-sent the zip with the dataset, It should be correct.

**Comment by zjr-ustc** [comment]
> Hello, [@cy94](https://github.com/cy94) [@zjr-ustc](https://github.com/zjr-ustc) I just re-sent the zip with the dataset, It should be correct.

thank you so much!

**Comment by cy94** [comment]
Thank you!

**Comment by doge0216** [comment]
@

> 你好，我已经把数据通过邮件发送给你了。

Hello, I have also encountered this issue, the current download link is returning a 404 error.
I would greatly appreciate it if you could send me the 3dmatch.zip file. My email address is [2015352829@qq.com]. Thank you very much for your assistance.
