### ISSUE TITLE
How to creat gt.info and gt.log files

### ISSUE THREAD

**Issue by lcxiha** [prs-eth/OverlapPredator#73]
Hello, 
    May I ask for  how the files of  gt.info, gt.log, and gt_overlap.log in OverlapPredator-main\configs\benchmarks\3DMatch\7-scenes-redkitchen generated? What information is required to generate these three files? I have been troubled by this place for a long time. Could you please help me answer it? I would greatly appreciate it!

**Comment by JosefT-TuDortmund** [comment]
I would also be interested in the details. Especially for the gt.info file.

**Comment by lcxiha** [comment]
Hello, do you know how the gt.log file is generated? Looking forward to your reply！ @JosefT-TuDortmund

**Comment by JosefT-TuDortmund** [comment]
Yes, I managed to generate them. I did it the following way:
1. First as a prerequisite you need to have all the transformations that align your point clouds in the world coordinate system. For the 3DMatch dataset they are stored in the cloud_bin_{id}.info.txt files.
2. The gt.log file essentially holds the pairwise relative transformations to align two point clouds. this can look like this:
`0	 1	 60`
` 9.96926560e-01	 6.68735757e-02	-4.06664421e-02	-1.15576939e-01	`
`-6.61289946e-02	 9.97617877e-01	 1.94008687e-02	-3.87705398e-02	`
` 4.18675510e-02	-1.66517807e-02	 9.98977765e-01	 1.14874890e-01	`
` 0.00000000e+00	 0.00000000e+00	 0.00000000e+00	 1.00000000e+00`
 
 The Transformation aligns the first point cloud (here idx 0) with the second (here indx 1). The 60 is the total number of point clouds in the sequence.
 
 Lets say you have the transformations for point cloud 0 and point cloud 1 given as T0 and T1.
 Then you can calculate the relative transformation as:
 `Trel = np.linalg.inv(T0) @ T1   # in python`
 
 For gt_info.log however, I am also clueless. Hope that this helps you :)

**Comment by lcxiha** [comment]
1.That is to say, if I have the rotation matrix and translation matrix of two frame point clouds in the world coordinate system, can I get the gt.log file? But I have another question: shouldn't the. log file be a log output file?
2.But I found out that the transformation matrix in the cloud_bin_{id}.info.txt files cannot correspond one-to-one with the transformation matrix in the gt.log file,and I am not quite sure about what does the first line in the cloud_bin_{id}.info.txt file mean.

**Comment by JosefT-TuDortmund** [comment]
Yes, the gt.log file corresponds to the relative transformations between the point clouds when they are aligned in the world coordinate system. Idk, how the original generation process of the .log files was. Perhaps the authors of the paper/code can bring some light into this discussion?

For me, the calculation of the relative transformations given the absolute poses within the cloud_bin_{id}.info.txt files worked fine as I described before. 
For the first line, the first two numbers are indices for the point clouds. The third number is the total number of point clouds for the scene.

**Comment by lcxiha** [comment]
Thank you. So I can understand that the generation of the gt.log file is not related to the cloud_bin_{id}.info.txt file, right?

About the gt.info file, some materials say that it is the Covariance matrix of the transformation matrix, but I don't understand it. @JosefT-TuDortmund

**Comment by lcxiha** [comment]
And I also found a problem: when I visualized the 3DMatch.pkl file, I found that the corresponding rotation matrix and the rotation matrix of the same pair of point cloud keyframes in the gt.log file were not the same, shouldn't they be the same? @JosefT-TuDortmund

**Comment by wzm2256** [comment]
For anyone who wish to know the meaning of gt.log file, please see http://redwood-data.org/indoor/fileformat.html

For anyone who wish to know how to compute the relative pose, I provide a concrete example based on @JosefT-TuDortmund 's answer.

```
        src_trans = np.loadtxt(src_trans_path, skiprows=1, usecols=None) # load a  *.info.txt file 
        tgt_trans = np.loadtxt(tgt_trans_path, skiprows=1, usecols=None) # load a  *.info.txt file 

        trans_full = np.matmul(np.linalg.inv(tgt_trans), src_trans) 

        assert np.abs(trans_full[:3, :3] - rot).sum() < 1e-2 # rot is the true rotation provided in gt.log or configs/indoor/3DMatch.pkl 
```

@lcxiha `` So I can understand that the generation of the gt.log file is not related to the cloud_bin_{id}.info.txt file, right?``  The statement is not correct.

**Comment by jun3333333** [comment]
Hi there,
I'm currently exploring the model and I've encountered an issue: the links to download the data and weights files seem to be unavailable. If you happen to have these files, could you please share them with me at 2373178085@qq.com? I'd greatly appreciate your assistance. Thank you so much!!

**Comment by jun3333333** [comment]
Hello, I encountered a FileNotFoundError after running: [Errno 2] No such file or directory: 'snapshot/indoor/est_traj/3DMatch/250/7-scenes-redkitchen/est.log'， There should be no predicted samples. If you have, please send a snapshot to my email: 2373178085@qq.com

**Comment by jun3333333** [comment]
snapshot/indoor/est_traj/3DMatch/250
0it [00:00, ?it/s]
gt_folder: configs/benchmarks/3DMatch
exp_dir: snapshot/indoor/est_traj/3DMatch/250
tsfm_est shape: (0,)
tsfm_est: []
Scene names: ['7-scenes-redkitchen', 'sun3d-home_at-home_at_scan1_2013_jan_1', 'sun3d-home_md-home_md_scan9_2012_sep_30', 'sun3d-hotel_uc-scan3', 'sun3d-hotel_umd-maryland_hotel1', 'sun3d-hotel_umd-maryland_hotel3', 'sun3d-mit_76_studyroom-76-1studyroom2', 'sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika']
Scene: 7-scenes-redkitchen, GT pairs: 506
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-home_at-home_at_scan1_2013_jan_1, GT pairs: 156
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-home_md-home_md_scan9_2012_sep_30, GT pairs: 208
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_uc-scan3, GT pairs: 226
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_umd-maryland_hotel1, GT pairs: 104
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_umd-maryland_hotel3, GT pairs: 54
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-mit_76_studyroom-76-1studyroom2, GT pairs: 292
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika, GT pairs: 77
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Traceback (most recent call last):
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 124, in <module>
    benchmark_predator(feats_scores, args.n_points, args.exp_dir, args.benchmark)
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 85, in benchmark_predator
    benchmark(exp_dir, gt_folder)
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark.py", line 304, in benchmark
    re = rotation_error(torch.from_numpy(ext_gt_traj[:,0:3,0:3]), torch.from_numpy(est_traj[:,0:3,0:3])).cpu().numpy()[np.array(c_flag)==0]
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark.py", line 27, in rotation_error
    e = torch.stack([(torch.trace(R_[_, :, :]) - 1) / 2 for _ in range(R_.shape[0])], dim=0).unsqueeze(1)
RuntimeError: stack expects a non-empty TensorList
snapshot/indoor/est_traj/3DMatch/500
0it [00:00, ?it/s]
gt_folder: configs/benchmarks/3DMatch
exp_dir: snapshot/indoor/est_traj/3DMatch/500
tsfm_est shape: (0,)
tsfm_est: []
Scene names: ['7-scenes-redkitchen', 'sun3d-home_at-home_at_scan1_2013_jan_1', 'sun3d-home_md-home_md_scan9_2012_sep_30', 'sun3d-hotel_uc-scan3', 'sun3d-hotel_umd-maryland_hotel1', 'sun3d-hotel_umd-maryland_hotel3', 'sun3d-mit_76_studyroom-76-1studyroom2', 'sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika']
Scene: 7-scenes-redkitchen, GT pairs: 506
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-home_at-home_at_scan1_2013_jan_1, GT pairs: 156
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-home_md-home_md_scan9_2012_sep_30, GT pairs: 208
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_uc-scan3, GT pairs: 226
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_umd-maryland_hotel1, GT pairs: 104
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_umd-maryland_hotel3, GT pairs: 54
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-mit_76_studyroom-76-1studyroom2, GT pairs: 292
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika, GT pairs: 77
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Traceback (most recent call last):
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 124, in <module>
    benchmark_predator(feats_scores, args.n_points, args.exp_dir, args.benchmark)
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 85, in benchmark_predator
    benchmark(exp_dir, gt_folder)
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark.py", line 304, in benchmark
    re = rotation_error(torch.from_numpy(ext_gt_traj[:,0:3,0:3]), torch.from_numpy(est_traj[:,0:3,0:3])).cpu().numpy()[np.array(c_flag)==0]
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark.py", line 27, in rotation_error
    e = torch.stack([(torch.trace(R_[_, :, :]) - 1) / 2 for _ in range(R_.shape[0])], dim=0).unsqueeze(1)
RuntimeError: stack expects a non-empty TensorList
snapshot/indoor/est_traj/3DMatch/1000
0it [00:00, ?it/s]
gt_folder: configs/benchmarks/3DMatch
exp_dir: snapshot/indoor/est_traj/3DMatch/1000
tsfm_est shape: (0,)
tsfm_est: []
Scene names: ['7-scenes-redkitchen', 'sun3d-home_at-home_at_scan1_2013_jan_1', 'sun3d-home_md-home_md_scan9_2012_sep_30', 'sun3d-hotel_uc-scan3', 'sun3d-hotel_umd-maryland_hotel1', 'sun3d-hotel_umd-maryland_hotel3', 'sun3d-mit_76_studyroom-76-1studyroom2', 'sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika']
Scene: 7-scenes-redkitchen, GT pairs: 506
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-home_at-home_at_scan1_2013_jan_1, GT pairs: 156
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-home_md-home_md_scan9_2012_sep_30, GT pairs: 208
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_uc-scan3, GT pairs: 226
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_umd-maryland_hotel1, GT pairs: 104
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_umd-maryland_hotel3, GT pairs: 54
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-mit_76_studyroom-76-1studyroom2, GT pairs: 292
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika, GT pairs: 77
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Traceback (most recent call last):
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 124, in <module>
    benchmark_predator(feats_scores, args.n_points, args.exp_dir, args.benchmark)
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 85, in benchmark_predator
    benchmark(exp_dir, gt_folder)
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark.py", line 304, in benchmark
    re = rotation_error(torch.from_numpy(ext_gt_traj[:,0:3,0:3]), torch.from_numpy(est_traj[:,0:3,0:3])).cpu().numpy()[np.array(c_flag)==0]
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark.py", line 27, in rotation_error
    e = torch.stack([(torch.trace(R_[_, :, :]) - 1) / 2 for _ in range(R_.shape[0])], dim=0).unsqueeze(1)
RuntimeError: stack expects a non-empty TensorList
snapshot/indoor/est_traj/3DMatch/2500
0it [00:00, ?it/s]
gt_folder: configs/benchmarks/3DMatch
exp_dir: snapshot/indoor/est_traj/3DMatch/2500
tsfm_est shape: (0,)
tsfm_est: []
Scene names: ['7-scenes-redkitchen', 'sun3d-home_at-home_at_scan1_2013_jan_1', 'sun3d-home_md-home_md_scan9_2012_sep_30', 'sun3d-hotel_uc-scan3', 'sun3d-hotel_umd-maryland_hotel1', 'sun3d-hotel_umd-maryland_hotel3', 'sun3d-mit_76_studyroom-76-1studyroom2', 'sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika']
Scene: 7-scenes-redkitchen, GT pairs: 506
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-home_at-home_at_scan1_2013_jan_1, GT pairs: 156
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-home_md-home_md_scan9_2012_sep_30, GT pairs: 208
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_uc-scan3, GT pairs: 226
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_umd-maryland_hotel1, GT pairs: 104
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_umd-maryland_hotel3, GT pairs: 54
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-mit_76_studyroom-76-1studyroom2, GT pairs: 292
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika, GT pairs: 77
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Traceback (most recent call last):
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 124, in <module>
    benchmark_predator(feats_scores, args.n_points, args.exp_dir, args.benchmark)
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 85, in benchmark_predator
    benchmark(exp_dir, gt_folder)
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark.py", line 304, in benchmark
    re = rotation_error(torch.from_numpy(ext_gt_traj[:,0:3,0:3]), torch.from_numpy(est_traj[:,0:3,0:3])).cpu().numpy()[np.array(c_flag)==0]
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark.py", line 27, in rotation_error
    e = torch.stack([(torch.trace(R_[_, :, :]) - 1) / 2 for _ in range(R_.shape[0])], dim=0).unsqueeze(1)
RuntimeError: stack expects a non-empty TensorList
snapshot/indoor/est_traj/3DMatch/5000
0it [00:00, ?it/s]
gt_folder: configs/benchmarks/3DMatch
exp_dir: snapshot/indoor/est_traj/3DMatch/5000
tsfm_est shape: (0,)
tsfm_est: []
Scene names: ['7-scenes-redkitchen', 'sun3d-home_at-home_at_scan1_2013_jan_1', 'sun3d-home_md-home_md_scan9_2012_sep_30', 'sun3d-hotel_uc-scan3', 'sun3d-hotel_umd-maryland_hotel1', 'sun3d-hotel_umd-maryland_hotel3', 'sun3d-mit_76_studyroom-76-1studyroom2', 'sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika']
Scene: 7-scenes-redkitchen, GT pairs: 506
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-home_at-home_at_scan1_2013_jan_1, GT pairs: 156
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-home_md-home_md_scan9_2012_sep_30, GT pairs: 208
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_uc-scan3, GT pairs: 226
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_umd-maryland_hotel1, GT pairs: 104
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_umd-maryland_hotel3, GT pairs: 54
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-mit_76_studyroom-76-1studyroom2, GT pairs: 292
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika, GT pairs: 77
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Traceback (most recent call last):
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 124, in <module>
    benchmark_predator(feats_scores, args.n_points, args.exp_dir, args.benchmark)
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 85, in benchmark_predator
    benchmark(exp_dir, gt_folder)
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark.py", line 304, in benchmark
    re = rotation_error(torch.from_numpy(ext_gt_traj[:,0:3,0:3]), torch.from_numpy(est_traj[:,0:3,0:3])).cpu().numpy()[np.array(c_flag)==0]
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark.py", line 27, in rotation_error
    e = torch.stack([(torch.trace(R_[_, :, :]) - 1) / 2 for _ in range(R_.shape[0])], dim=0).unsqueeze(1)
RuntimeError: stack expects a non-empty TensorList
(pytorch1) user@user-System-Product-Name:~/OverlapPredator.Mink-master$ for N_POINTS in 250 500 1000 2500 5000
do
  python scripts/evaluate_predator.py --source_path snapshot/indoor/3DMatch --n_points $N_POINTS --benchmark 3DMatch --exp_dir snapshot/indoor/est_traj --sampling prob
done
snapshot/indoor/est_traj/3DMatch/250
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 124, in <module>
    benchmark_predator(feats_scores, args.n_points, args.exp_dir, args.benchmark)
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 81, in benchmark_predator
    write_est_trajectory(gt_folder, exp_dir, tsfm_est)
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark_utils.py", line 67, in write_est_trajectory
    est_traj.append(tsfm_est[count])
IndexError: index 0 is out of bounds for axis 0 with size 0
snapshot/indoor/est_traj/3DMatch/500
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 124, in <module>
    benchmark_predator(feats_scores, args.n_points, args.exp_dir, args.benchmark)
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 81, in benchmark_predator
    write_est_trajectory(gt_folder, exp_dir, tsfm_est)
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark_utils.py", line 67, in write_est_trajectory
    est_traj.append(tsfm_est[count])
IndexError: index 0 is out of bounds for axis 0 with size 0
snapshot/indoor/est_traj/3DMatch/1000
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 124, in <module>
    benchmark_predator(feats_scores, args.n_points, args.exp_dir, args.benchmark)
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 81, in benchmark_predator
    write_est_trajectory(gt_folder, exp_dir, tsfm_est)
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark_utils.py", line 67, in write_est_trajectory
    est_traj.append(tsfm_est[count])
IndexError: index 0 is out of bounds for axis 0 with size 0
snapshot/indoor/est_traj/3DMatch/2500
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 124, in <module>
    benchmark_predator(feats_scores, args.n_points, args.exp_dir, args.benchmark)
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 81, in benchmark_predator
    write_est_trajectory(gt_folder, exp_dir, tsfm_est)
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark_utils.py", line 67, in write_est_trajectory
    est_traj.append(tsfm_est[count])
IndexError: index 0 is out of bounds for axis 0 with size 0
snapshot/indoor/est_traj/3DMatch/5000
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 124, in <module>
    benchmark_predator(feats_scores, args.n_points, args.exp_dir, args.benchmark)
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 81, in benchmark_predator
    write_est_trajectory(gt_folder, exp_dir, tsfm_est)
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark_utils.py", line 67, in write_est_trajectory
    est_traj.append(tsfm_est[count])
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by jun3333333** [comment]
Hello author, I use my own source cloud and target cloud files to run demo.py for registration, the effect is not very good, may I ask how I can improve my registration effect？，Please send it to my email：[2373178085@qq.com](mailto:2373178085@qq.com)
