### ISSUE TITLE
Questions about producing the newest results with the newest codes

### ISSUE THREAD

**Issue by HowLeeHi** [prs-eth/OverlapPredator#75]
Hi!
Thank you so much for this amazing work!

I'm trying to produce the results with your newest codes.
I followed the guidance in README and got beautiful results as follows:

1. For 3DMatch_250_prob:
```
Scene	¦ prec.	¦ rec.	¦ re	¦ te	¦ samples	¦
Kitchen	¦ 0.958	¦ 0.958	¦ 2.382	¦ 0.065	¦ 449¦
Home 1	¦ 0.906	¦ 0.906	¦ 2.618	¦ 0.087	¦ 106¦
Home 2	¦ 0.761	¦ 0.761	¦ 3.299	¦ 0.085	¦ 159¦
Hotel 1	¦ 0.945	¦ 0.945	¦ 2.425	¦ 0.083	¦ 182¦
Hotel 2	¦ 0.923	¦ 0.923	¦ 2.674	¦ 0.101	¦  78¦
Hotel 3	¦ 0.808	¦ 0.808	¦ 2.450	¦ 0.074	¦  26¦
Study	¦ 0.808	¦ 0.808	¦ 2.898	¦ 0.098	¦ 234¦
MIT Lab	¦ 0.733	¦ 0.733	¦ 2.916	¦ 0.106	¦  45¦
Mean precision: 0.855: +- 0.082
Weighted precision: 0.887
Mean median RRE: 2.708: +- 0.294
Mean median RTE: 0.087: +- 0.013
Inlier ratio w_mutual: 0.467 : +- 0.045
Feature match recall w_mutual: 0.968 : +- 0.024
Inlier ratio wo_mutual: 0.358 : +- 0.039
Feature match recall wo_mutual: 0.958 : +- 0.029
```

2. For 3DMatch_500_prob:
```
Scene	¦ prec.	¦ rec.	¦ re	¦ te	¦ samples	¦
Kitchen	¦ 0.967	¦ 0.967	¦ 1.971	¦ 0.057	¦ 449¦
Home 1	¦ 0.953	¦ 0.953	¦ 1.908	¦ 0.065	¦ 106¦
Home 2	¦ 0.780	¦ 0.780	¦ 2.552	¦ 0.081	¦ 159¦
Hotel 1	¦ 0.973	¦ 0.973	¦ 1.865	¦ 0.064	¦ 182¦
Hotel 2	¦ 0.923	¦ 0.923	¦ 2.322	¦ 0.069	¦  78¦
Hotel 3	¦ 0.808	¦ 0.808	¦ 2.752	¦ 0.046	¦  26¦
Study	¦ 0.833	¦ 0.833	¦ 2.440	¦ 0.094	¦ 234¦
MIT Lab	¦ 0.778	¦ 0.778	¦ 2.038	¦ 0.082	¦  45¦
Mean precision: 0.877: +- 0.080
Weighted precision: 0.906
Mean median RRE: 2.231: +- 0.310
Mean median RTE: 0.070: +- 0.014
Inlier ratio w_mutual: 0.510 : +- 0.044
Feature match recall w_mutual: 0.965 : +- 0.022
Inlier ratio wo_mutual: 0.407 : +- 0.043
Feature match recall wo_mutual: 0.957 : +- 0.036
```

3. For 3DMatch_1000_prob:
```
Scene	¦ prec.	¦ rec.	¦ re	¦ te	¦ samples	¦
Kitchen	¦ 0.976	¦ 0.976	¦ 1.845	¦ 0.052	¦ 449¦
Home 1	¦ 0.972	¦ 0.972	¦ 1.938	¦ 0.067	¦ 106¦
Home 2	¦ 0.780	¦ 0.780	¦ 2.389	¦ 0.077	¦ 159¦
Hotel 1	¦ 0.978	¦ 0.978	¦ 1.826	¦ 0.068	¦ 182¦
Hotel 2	¦ 0.949	¦ 0.949	¦ 1.800	¦ 0.069	¦  78¦
Hotel 3	¦ 0.808	¦ 0.808	¦ 2.414	¦ 0.053	¦  26¦
Study	¦ 0.846	¦ 0.846	¦ 2.227	¦ 0.090	¦ 234¦
MIT Lab	¦ 0.778	¦ 0.778	¦ 2.281	¦ 0.070	¦  45¦
Mean precision: 0.886: +- 0.085
Weighted precision: 0.916
Mean median RRE: 2.090: +- 0.247
Mean median RTE: 0.068: +- 0.011
Inlier ratio w_mutual: 0.532 : +- 0.044
Feature match recall w_mutual: 0.966 : +- 0.022
Inlier ratio wo_mutual: 0.434 : +- 0.043
Feature match recall wo_mutual: 0.962 : +- 0.030
```

4. For 3DMatch_2500_prob:
```
Scene	¦ prec.	¦ rec.	¦ re	¦ te	¦ samples	¦
Kitchen	¦ 0.971	¦ 0.971	¦ 1.770	¦ 0.049	¦ 449¦
Home 1	¦ 0.972	¦ 0.972	¦ 1.883	¦ 0.064	¦ 106¦
Home 2	¦ 0.761	¦ 0.761	¦ 2.508	¦ 0.074	¦ 159¦
Hotel 1	¦ 0.984	¦ 0.984	¦ 1.805	¦ 0.060	¦ 182¦
Hotel 2	¦ 0.936	¦ 0.936	¦ 1.800	¦ 0.061	¦  78¦
Hotel 3	¦ 0.885	¦ 0.885	¦ 2.672	¦ 0.062	¦  26¦
Study	¦ 0.850	¦ 0.850	¦ 2.032	¦ 0.078	¦ 234¦
MIT Lab	¦ 0.800	¦ 0.800	¦ 1.882	¦ 0.078	¦  45¦
Mean precision: 0.895: +- 0.079
Weighted precision: 0.915
Mean median RRE: 2.044: +- 0.327
Mean median RTE: 0.066: +- 0.009
Inlier ratio w_mutual: 0.542 : +- 0.043
Feature match recall w_mutual: 0.966 : +- 0.020
Inlier ratio wo_mutual: 0.444 : +- 0.043
Feature match recall wo_mutual: 0.961 : +- 0.028
```

5. For 3DMatch_5000_prob:
```
Scene	¦ prec.	¦ rec.	¦ re	¦ te	¦ samples	¦
Kitchen	¦ 0.976	¦ 0.976	¦ 1.765	¦ 0.050	¦ 449¦
Home 1	¦ 0.953	¦ 0.953	¦ 1.681	¦ 0.054	¦ 106¦
Home 2	¦ 0.748	¦ 0.748	¦ 2.293	¦ 0.073	¦ 159¦
Hotel 1	¦ 0.978	¦ 0.978	¦ 1.785	¦ 0.063	¦ 182¦
Hotel 2	¦ 0.962	¦ 0.962	¦ 1.598	¦ 0.063	¦  78¦
Hotel 3	¦ 0.846	¦ 0.846	¦ 2.511	¦ 0.058	¦  26¦
Study	¦ 0.838	¦ 0.838	¦ 1.952	¦ 0.081	¦ 234¦
MIT Lab	¦ 0.756	¦ 0.756	¦ 1.748	¦ 0.075	¦  45¦
Mean precision: 0.882: +- 0.091
Weighted precision: 0.909
Mean median RRE: 1.917: +- 0.300
Mean median RTE: 0.065: +- 0.010
Inlier ratio w_mutual: 0.535 : +- 0.042
Feature match recall w_mutual: 0.969 : +- 0.019
Inlier ratio wo_mutual: 0.430 : +- 0.041
Feature match recall wo_mutual: 0.957 : +- 0.032
```

For a summary, the recall rates on 3DMatch are

|5000 | 2500 | 1000 | 500 | 250 |
|--------|--------|--------|--------|--------|
| 88.2 | 89.5 | 88.6 | 87.7 | 85.5 | 

However, I find that you have fixed a bug and got a higher performance, as follows,
![image](https://github.com/prs-eth/OverlapPredator/assets/43001557/1ef03c54-a827-42dd-bed9-578c5b55f4c6)
which is slightly better than what I produced with your newest codes. What's more, It seems like the results I produced are closer to the ones before you fixed the bug as follows:
<img width="834" alt="image" src="https://github.com/prs-eth/OverlapPredator/assets/43001557/34dc7248-4549-4b85-a01a-742333486578">

Then, I try producing the results another time. This time, I got
|5000 | 2500 | 1000 | 500 | 250 |
|--------|--------|--------|--------|--------|
| 88.6 | 87.6 | 88.8 | 86.8 | 85.3 | 

which is still closer to the results before fixing the bug.

To verify I got the right codes, I downloaded your released weight and test. It seems the results are correct and have few differences with the results you updated after fixing the bug.
|5000 | 2500 | 1000 | 500 | 250 |
|--------|--------|--------|--------|--------|
| 89.0 | 89.7| 90.2 | 90.1 | 85.7| 

This has confused me for a long time. Could you help me figure out what's wrong with my training phase?
I run your codes on one 2080Ti without any modification on the config.
Thanks a lot!

**Comment by jun3333333** [comment]
Hi there,
I'm currently exploring the model and I've encountered an issue: the links to download the data and weights files seem to be unavailable. If you happen to have these files, could you please share them with me at 2373178085@qq.com? I'd greatly appreciate your assistance. Thank you so much!!

**Comment by jun3333333** [comment]
Hello, I encountered a FileNotFoundError after running: [Errno 2] No such file or directory: 'snapshot/indoor/est_traj/3DMatch/250/7-scenes-redkitchen/est.log'， There should be no predicted samples. If you have, please send a snapshot to my email: 2373178085@qq.com

**Comment by jun3333333** [comment]
snapshot/indoor/est_traj/3DMatch/250
0it [00:00, ?it/s]
gt_folder: configs/benchmarks/3DMatch
exp_dir: snapshot/indoor/est_traj/3DMatch/250
tsfm_est shape: (0,)
tsfm_est: []
Scene names: ['7-scenes-redkitchen', 'sun3d-home_at-home_at_scan1_2013_jan_1', 'sun3d-home_md-home_md_scan9_2012_sep_30', 'sun3d-hotel_uc-scan3', 'sun3d-hotel_umd-maryland_hotel1', 'sun3d-hotel_umd-maryland_hotel3', 'sun3d-mit_76_studyroom-76-1studyroom2', 'sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika']
Scene: 7-scenes-redkitchen, GT pairs: 506
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-home_at-home_at_scan1_2013_jan_1, GT pairs: 156
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-home_md-home_md_scan9_2012_sep_30, GT pairs: 208
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_uc-scan3, GT pairs: 226
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_umd-maryland_hotel1, GT pairs: 104
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_umd-maryland_hotel3, GT pairs: 54
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-mit_76_studyroom-76-1studyroom2, GT pairs: 292
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika, GT pairs: 77
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Traceback (most recent call last):
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 124, in <module>
    benchmark_predator(feats_scores, args.n_points, args.exp_dir, args.benchmark)
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 85, in benchmark_predator
    benchmark(exp_dir, gt_folder)
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark.py", line 304, in benchmark
    re = rotation_error(torch.from_numpy(ext_gt_traj[:,0:3,0:3]), torch.from_numpy(est_traj[:,0:3,0:3])).cpu().numpy()[np.array(c_flag)==0]
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark.py", line 27, in rotation_error
    e = torch.stack([(torch.trace(R_[_, :, :]) - 1) / 2 for _ in range(R_.shape[0])], dim=0).unsqueeze(1)
RuntimeError: stack expects a non-empty TensorList
snapshot/indoor/est_traj/3DMatch/500
0it [00:00, ?it/s]
gt_folder: configs/benchmarks/3DMatch
exp_dir: snapshot/indoor/est_traj/3DMatch/500
tsfm_est shape: (0,)
tsfm_est: []
Scene names: ['7-scenes-redkitchen', 'sun3d-home_at-home_at_scan1_2013_jan_1', 'sun3d-home_md-home_md_scan9_2012_sep_30', 'sun3d-hotel_uc-scan3', 'sun3d-hotel_umd-maryland_hotel1', 'sun3d-hotel_umd-maryland_hotel3', 'sun3d-mit_76_studyroom-76-1studyroom2', 'sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika']
Scene: 7-scenes-redkitchen, GT pairs: 506
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-home_at-home_at_scan1_2013_jan_1, GT pairs: 156
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-home_md-home_md_scan9_2012_sep_30, GT pairs: 208
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_uc-scan3, GT pairs: 226
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_umd-maryland_hotel1, GT pairs: 104
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_umd-maryland_hotel3, GT pairs: 54
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-mit_76_studyroom-76-1studyroom2, GT pairs: 292
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika, GT pairs: 77
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Traceback (most recent call last):
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 124, in <module>
    benchmark_predator(feats_scores, args.n_points, args.exp_dir, args.benchmark)
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 85, in benchmark_predator
    benchmark(exp_dir, gt_folder)
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark.py", line 304, in benchmark
    re = rotation_error(torch.from_numpy(ext_gt_traj[:,0:3,0:3]), torch.from_numpy(est_traj[:,0:3,0:3])).cpu().numpy()[np.array(c_flag)==0]
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark.py", line 27, in rotation_error
    e = torch.stack([(torch.trace(R_[_, :, :]) - 1) / 2 for _ in range(R_.shape[0])], dim=0).unsqueeze(1)
RuntimeError: stack expects a non-empty TensorList
snapshot/indoor/est_traj/3DMatch/1000
0it [00:00, ?it/s]
gt_folder: configs/benchmarks/3DMatch
exp_dir: snapshot/indoor/est_traj/3DMatch/1000
tsfm_est shape: (0,)
tsfm_est: []
Scene names: ['7-scenes-redkitchen', 'sun3d-home_at-home_at_scan1_2013_jan_1', 'sun3d-home_md-home_md_scan9_2012_sep_30', 'sun3d-hotel_uc-scan3', 'sun3d-hotel_umd-maryland_hotel1', 'sun3d-hotel_umd-maryland_hotel3', 'sun3d-mit_76_studyroom-76-1studyroom2', 'sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika']
Scene: 7-scenes-redkitchen, GT pairs: 506
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-home_at-home_at_scan1_2013_jan_1, GT pairs: 156
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-home_md-home_md_scan9_2012_sep_30, GT pairs: 208
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_uc-scan3, GT pairs: 226
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_umd-maryland_hotel1, GT pairs: 104
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_umd-maryland_hotel3, GT pairs: 54
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-mit_76_studyroom-76-1studyroom2, GT pairs: 292
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika, GT pairs: 77
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Traceback (most recent call last):
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 124, in <module>
    benchmark_predator(feats_scores, args.n_points, args.exp_dir, args.benchmark)
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 85, in benchmark_predator
    benchmark(exp_dir, gt_folder)
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark.py", line 304, in benchmark
    re = rotation_error(torch.from_numpy(ext_gt_traj[:,0:3,0:3]), torch.from_numpy(est_traj[:,0:3,0:3])).cpu().numpy()[np.array(c_flag)==0]
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark.py", line 27, in rotation_error
    e = torch.stack([(torch.trace(R_[_, :, :]) - 1) / 2 for _ in range(R_.shape[0])], dim=0).unsqueeze(1)
RuntimeError: stack expects a non-empty TensorList
snapshot/indoor/est_traj/3DMatch/2500
0it [00:00, ?it/s]
gt_folder: configs/benchmarks/3DMatch
exp_dir: snapshot/indoor/est_traj/3DMatch/2500
tsfm_est shape: (0,)
tsfm_est: []
Scene names: ['7-scenes-redkitchen', 'sun3d-home_at-home_at_scan1_2013_jan_1', 'sun3d-home_md-home_md_scan9_2012_sep_30', 'sun3d-hotel_uc-scan3', 'sun3d-hotel_umd-maryland_hotel1', 'sun3d-hotel_umd-maryland_hotel3', 'sun3d-mit_76_studyroom-76-1studyroom2', 'sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika']
Scene: 7-scenes-redkitchen, GT pairs: 506
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-home_at-home_at_scan1_2013_jan_1, GT pairs: 156
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-home_md-home_md_scan9_2012_sep_30, GT pairs: 208
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_uc-scan3, GT pairs: 226
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_umd-maryland_hotel1, GT pairs: 104
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_umd-maryland_hotel3, GT pairs: 54
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-mit_76_studyroom-76-1studyroom2, GT pairs: 292
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika, GT pairs: 77
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Traceback (most recent call last):
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 124, in <module>
    benchmark_predator(feats_scores, args.n_points, args.exp_dir, args.benchmark)
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 85, in benchmark_predator
    benchmark(exp_dir, gt_folder)
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark.py", line 304, in benchmark
    re = rotation_error(torch.from_numpy(ext_gt_traj[:,0:3,0:3]), torch.from_numpy(est_traj[:,0:3,0:3])).cpu().numpy()[np.array(c_flag)==0]
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark.py", line 27, in rotation_error
    e = torch.stack([(torch.trace(R_[_, :, :]) - 1) / 2 for _ in range(R_.shape[0])], dim=0).unsqueeze(1)
RuntimeError: stack expects a non-empty TensorList
snapshot/indoor/est_traj/3DMatch/5000
0it [00:00, ?it/s]
gt_folder: configs/benchmarks/3DMatch
exp_dir: snapshot/indoor/est_traj/3DMatch/5000
tsfm_est shape: (0,)
tsfm_est: []
Scene names: ['7-scenes-redkitchen', 'sun3d-home_at-home_at_scan1_2013_jan_1', 'sun3d-home_md-home_md_scan9_2012_sep_30', 'sun3d-hotel_uc-scan3', 'sun3d-hotel_umd-maryland_hotel1', 'sun3d-hotel_umd-maryland_hotel3', 'sun3d-mit_76_studyroom-76-1studyroom2', 'sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika']
Scene: 7-scenes-redkitchen, GT pairs: 506
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-home_at-home_at_scan1_2013_jan_1, GT pairs: 156
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-home_md-home_md_scan9_2012_sep_30, GT pairs: 208
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_uc-scan3, GT pairs: 226
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_umd-maryland_hotel1, GT pairs: 104
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-hotel_umd-maryland_hotel3, GT pairs: 54
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-mit_76_studyroom-76-1studyroom2, GT pairs: 292
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Scene: sun3d-mit_lab_hj-lab_hj_tea_nov_2_2012_scan1_erika, GT pairs: 77
Warning: count 0 exceeds tsfm_est length 0. Skipping remaining pairs.
Traceback (most recent call last):
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 124, in <module>
    benchmark_predator(feats_scores, args.n_points, args.exp_dir, args.benchmark)
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 85, in benchmark_predator
    benchmark(exp_dir, gt_folder)
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark.py", line 304, in benchmark
    re = rotation_error(torch.from_numpy(ext_gt_traj[:,0:3,0:3]), torch.from_numpy(est_traj[:,0:3,0:3])).cpu().numpy()[np.array(c_flag)==0]
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark.py", line 27, in rotation_error
    e = torch.stack([(torch.trace(R_[_, :, :]) - 1) / 2 for _ in range(R_.shape[0])], dim=0).unsqueeze(1)
RuntimeError: stack expects a non-empty TensorList
(pytorch1) user@user-System-Product-Name:~/OverlapPredator.Mink-master$ for N_POINTS in 250 500 1000 2500 5000
do
  python scripts/evaluate_predator.py --source_path snapshot/indoor/3DMatch --n_points $N_POINTS --benchmark 3DMatch --exp_dir snapshot/indoor/est_traj --sampling prob
done
snapshot/indoor/est_traj/3DMatch/250
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 124, in <module>
    benchmark_predator(feats_scores, args.n_points, args.exp_dir, args.benchmark)
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 81, in benchmark_predator
    write_est_trajectory(gt_folder, exp_dir, tsfm_est)
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark_utils.py", line 67, in write_est_trajectory
    est_traj.append(tsfm_est[count])
IndexError: index 0 is out of bounds for axis 0 with size 0
snapshot/indoor/est_traj/3DMatch/500
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 124, in <module>
    benchmark_predator(feats_scores, args.n_points, args.exp_dir, args.benchmark)
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 81, in benchmark_predator
    write_est_trajectory(gt_folder, exp_dir, tsfm_est)
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark_utils.py", line 67, in write_est_trajectory
    est_traj.append(tsfm_est[count])
IndexError: index 0 is out of bounds for axis 0 with size 0
snapshot/indoor/est_traj/3DMatch/1000
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 124, in <module>
    benchmark_predator(feats_scores, args.n_points, args.exp_dir, args.benchmark)
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 81, in benchmark_predator
    write_est_trajectory(gt_folder, exp_dir, tsfm_est)
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark_utils.py", line 67, in write_est_trajectory
    est_traj.append(tsfm_est[count])
IndexError: index 0 is out of bounds for axis 0 with size 0
snapshot/indoor/est_traj/3DMatch/2500
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 124, in <module>
    benchmark_predator(feats_scores, args.n_points, args.exp_dir, args.benchmark)
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 81, in benchmark_predator
    write_est_trajectory(gt_folder, exp_dir, tsfm_est)
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark_utils.py", line 67, in write_est_trajectory
    est_traj.append(tsfm_est[count])
IndexError: index 0 is out of bounds for axis 0 with size 0
snapshot/indoor/est_traj/3DMatch/5000
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 124, in <module>
    benchmark_predator(feats_scores, args.n_points, args.exp_dir, args.benchmark)
  File "/home/user/OverlapPredator.Mink-master/scripts/evaluate_predator.py", line 81, in benchmark_predator
    write_est_trajectory(gt_folder, exp_dir, tsfm_est)
  File "/home/user/OverlapPredator.Mink-master/lib/benchmark_utils.py", line 67, in write_est_trajectory
    est_traj.append(tsfm_est[count])
IndexError: index 0 is out of bounds for axis 0 with size 0

**Comment by jun3333333** [comment]
Hello author, I use my own source cloud and target cloud files to run demo.py for registration, the effect is not very good, may I ask how I can improve my registration effect？，Please send it to my email：[2373178085@qq.com](mailto:2373178085@qq.com)
